### PR TITLE
Bugfix for accessors

### PR DESCRIPTION
**Pull request by agilmore2**
Yep, I broke it. This looks like a good fix.
How to indicate distributed version has fix?

### CODE REVIEW

**Comment by Hurricaaane** [comment]
that's what I get for not checking my messages daily, I'll look into it

**Comment by Hurricaaane** [comment]
I pushed the zip you distributed up to the website

**Comment by agilmore2** [comment]
Wow. Thanks!

**Comment by agilmore2** [comment]
How are things going? From this bug, it's clear I don't know as much as I
thought I did. ;)

**Comment by Hurricaaane** [comment]
I want to have actions speak in place of my words, so I'm not posting anything right now ; as a side effect I'm not reading forums daily either, so I don't notice things the moment I should be.

**Pull request merged**
